[Obligatorio] 9. Despliegue del texto de puntaje en la parte superior con su texto 1-UP
Laurarestrepo03/Ocarina-Galaxian pull request #33
Opened 2024-05-04 01:37 UTC by lacortesz

https://github.com/Laurarestrepo03/Ocarina-Galaxian/assets/124101392/7a6c63ad-631c-41c9-b1ce-cb05ef50486a

Incluye textos estaticos_
- 1UP 
- 00 (1UP Value)
- HI-SCORE
- 1000 (Hi-score value)

2024-05-04 01:45 UTC, Laurarestrepo03 requested changes

2024-05-04 01:45 UTC, Laurarestrepo03 commented on src/engine/services/fonts_services.py
> +    def get(self, path:str, size:int) -> pygame.font:
Podemos cambiar esta función para que la llave sea una combinación del path +  el tamaño? Tipo "Calibri-12". Es que el `size != self._fonts` no estoy muy segura si cumple la función que queremos. Yo hice algo parecido para el ejercicio individual si necesitas ayuda. Gracias!

2024-05-04 01:59 UTC, lacortesz commented on src/engine/services/fonts_services.py
> +    def get(self, path:str, size:int) -> pygame.font:
Efectivamente la condicion esta mal, pero se puede quitar y funciona por que valida que exista el path. Si se envia el path + el tamaño tocaria despues dividir el string porque la funcion pygame.font.Font(path, size) recibe los dos parametros aparte, seria al menos una linea mas, me cuentas y lo revisamos, por lo pronto cerre el PR

2024-05-04 02:02 UTC, Laurarestrepo03 commented on src/engine/services/fonts_services.py
> +    def get(self, path:str, size:int) -> pygame.font:
Sip, tienes razón, solo es una línes. Algo así, mira:

```python
def get(self, path: str, size:int) -> None:
        font_key = path + "-" + str(size)
        if font_key not in self._fonts:
            self._fonts[font_key] = pygame.font.Font(path, size)
        return self._fonts[font_key]
```

Puedes hacer trabajar sobre este mismo PR. :)

2024-05-04 19:39 UTC, Laurarestrepo03 commented
@lacortesz En el PR #34 cambiamos la función, entonces si quieres haz merge con main y quedaría este PR, gracias!

2024-05-04 21:49 UTC, Laurarestrepo03 commented
@lacortesz Ahora que lo pienso, habría que implementar un sistema que actualice el texto de puntaje. Mira [esta documentación](https://gamefaqs.gamespot.com/arcade/583825-galaxian/faqs/32227) que dice cuántos puntos da cada enemigo (sección 5).

2024-05-04 21:52 UTC, Laurarestrepo03 commented
> @lacortesz Ahora que lo pienso, habría que implementar un sistema que actualice el texto de puntaje. Mira [esta documentación](https://gamefaqs.gamespot.com/arcade/583825-galaxian/faqs/32227) que dice cuántos puntos da cada enemigo (sección 5).

Revisa el puntaje de convoy, porque de momento no se salen del grupo. Gracias!

2024-05-09 16:07 UTC, lacortesz commented
@Laurarestrepo03, este feature lo tenia para el despliegue del texto superior estatico, para incluir el sistema que actualiza el puntaje deberiamos cambiarle el nombre a este.
@miguelangel1021 creo que la funcion create_pause_text se puede refactorizar para tener un create_text generico pata todos los textos, me cuentas si te parece y lo hago en este de una vez

2024-05-09 16:27 UTC, Laurarestrepo03 commented
> @Laurarestrepo03, este feature lo tenia para el despliegue del texto superior estatico, para incluir el sistema que actualiza el puntaje deberiamos cambiarle el nombre a este. @miguelangel1021 creo que la funcion create_pause_text se puede refactorizar para tener un create_text generico pata todos los textos, me cuentas si te parece y lo hago en este de una vez

Por "cambiar el nombre a este" te refieres a cambiar el nombre de qué? Por cierto, porfa haz merge con main que hay conflictos

2024-05-10 00:03 UTC, lacortesz commented
Se adiciona funcionalidades:
- Actualizacion score
- Actualizacion High Score
- Almacena el nuevo high score para que se muestre al iniciar el juego

https://github.com/Laurarestrepo03/Ocarina-Galaxian/assets/124101392/da6c53ea-cd14-4e2f-ab40-f7edb44d6a67

![MISO - Invaders! 09_05_2024 7_01_00 p  m](https://github.com/Laurarestrepo03/Ocarina-Galaxian/assets/124101392/a2648cc7-172f-4f57-89db-8bcb06080d55)

2024-05-10 00:10 UTC, leonardo-bp approved these changes
Ok.

2024-05-10 00:26 UTC, Laurarestrepo03 approved these changes
Gracias por los cambios!

2024-05-10 00:27 UTC, merged