Implementación del texto ready al inicio del juego.
Laurarestrepo03/Ocarina-Galaxian pull request #37
Opened 2024-05-04 22:41 UTC by miguelangel1021

Se delego el create player y create level a la funcion update cuando se cumpla que hayan pasado más de 3 segundos desde el inicio del juego.

2024-05-05 02:31 UTC, Laurarestrepo03 requested changes
Solamente hice una revisión del juego ejecutado y no del código, pero noté esto: hay una discrepancia entre el ejemplo que nos dan y el juego real: 
- En el ejemplo, el jugador se crea al mismo tiempo que el READY, y se puede mover. Sin embargo, **no** puede disparar
- En el juego real, los _enemigos_ se crean al mismo tiempo que el READY, y el jugador hasta después de que desaparezca el texto

Te recomiendo preguntar a ver qué es mejor, porque de todas maneras sí tendrías que cambiar eso.

Otra cosa es que también se crean los demás textos estáticos como el 1UP y eso al mismo tiempo que el READY. Como no está implementado todavía puedes dejar este PR abierto y esperar, o mergearlo (cuando hayas hecho los cambios de arriba) y dejarlo como un fix para después

Igual lo que vas está súper, gracias!

2024-05-05 02:36 UTC, Laurarestrepo03 commented
Otra cosa es el color del texto. En el ejemplo es blanco, pero en el juego real es rojo. Tu decisión igual.

2024-05-11 21:48 UTC, Laurarestrepo03 commented
@miguelangel1021 Gracias por los cambios que llevas! Un detalle pequeño pero la bala sí debería aparecer el mismo tiempo que el ready, solo que no se puede disparar

2024-05-11 21:57 UTC, Laurarestrepo03 commented on src/engine/game_engine.py
> +        if self.start_game and 3<= self.current_time:
No sé si esto se pueda, tener condicionales en el update. Si no estoy mal, en el doc de avance el profe dijo que tener ifs en el update suena a que se debe hacer otro sistema. Podemos confirmar con él igual

2024-05-12 05:44 UTC, miguelangel1021 commented on src/engine/game_engine.py
> +        if self.start_game and 3<= self.current_time:
Lau, implemente las escenas, mantuve todos los cambios comentados en los archivos por si no estaban de acuerdo con este cambio ya que es bastante grande, ya corregí lo de la bala, para que aparezca al mismo tiempo que el ready. Aparentemente funciona todo bien, corregí un error, pues al cambiar de escena y mantener la tecla izquierda o derecha, se bloqueaba la nave debido a la verificación que se hace al tener dos teclas por movimiento (izquierda y A, por ejemplo, la verificación de if ...keys_left == 0). Pero pues ya no se bloquea. Revísalo y me dices si está bien en no. Al hacer las escenas, es más fácil por ejemplo ganar los bonos del menú, ya que es casi un reciclado de PlayScene o IntroScene. Me comentas que te parece.

2024-05-12 05:47 UTC, miguelangel1021 commented on src/engine/game_engine.py
> +        if self.start_game and 3<= self.current_time:
Otra cosita que me percate, no sé si es bono o no, pero, cuando la nave es golpeada por una bala, la nave no debería desaparecer por un momento, lo digo porque está así en el ejemplo. Para que la persona que hizo el sistema de colisión pues agregue esa funcionalidad. Ten buena noche jajaa.

2024-05-12 06:11 UTC, Laurarestrepo03 commented
Vi que hiciste hartas cosas, entonces primero muchas gracias por los cambios. Hay una detalle de todas maneras jaja. Creo que esto es un "problema" más grande pero un ejemplo es que si tú estás moviendo la nave durante la primera escena y cambia a la del juego, se queda quieta. No se bloquea, pero tienes que volver a presionar el botón para que funcione. En el ejemplo tú puedes seguir moviéndote durante esa transición de escenas. Entonces, creo que el problema más grande es que estamos creando las cosas otra vez. Creería que podría haber un sistema general o algo que pueda manejar unas mismas entidades y sistemas al mismo tiempo. De todas maneras, si quieres deja así por ahora y en el doc de avance podemos preguntar si esta partecita está bien, referenciamos este PR para que lo revisen.

Lo otro es que no entendí muy bien lo que me dijiste de  "la nave no debería desaparecer por un momento". No sé si esto responde tu comentario, pero de momento no estamos haciendo desaparecer la nave porque no está implementado el GAME OVER, eso sería parte del issue #11.

2024-05-12 16:14 UTC, miguelangel1021 commented
Vale, si lo note ayer ajaja, y pues como dices, es porque se crea nuevamente la nave y lo malo es que así funcionan las escenas. Sin embargo, déjame entonces pensar que hacer con eso. En el segundo comentario, me refería a que cada vez que explota la nave, esta desaparece por unos segundos, para nuevamente reaparecer en caso de que el número de vidas no llegue a 0 y se reanuda el juego. Como esta en este momento, simplemente se lanza la animación de la explosión. Por eso mismo comenté que si no era algo obligatorio. Gracias por los comentarios Lau.

2024-05-12 16:33 UTC, Laurarestrepo03 commented
Valee, gracias a ti @miguelangel1021. Si algo, con respecto a lo del problema de volver a crear, voy a preguntar si estaba bien como lo tenías antes que no estaba ese problema.

2024-05-12 20:55 UTC, Laurarestrepo03 commented
De lo que veo que cambiaste ya considero que funciona muuucho mejor, será esperar los comentarios del profe. Muchas gracias!!

2024-05-18 01:24 UTC, Laurarestrepo03 commented
Cerrado porque se trabajaré sobre el PR #55

2024-05-18 01:24 UTC, closed without merging