Se ajusta la creación y parpadeo de las estrellas eliminando CStarfield y añadiendo CBlink y system_blink
Laurarestrepo03/Ocarina-Galaxian pull request #47
Opened 2024-05-10 05:33 UTC by leonardo-bp

Se ajusta la creación y parpadeo de las estrellas eliminando CStarfield y añadiendo CBlink y system_blink

2024-05-10 23:25 UTC, Laurarestrepo03 requested changes
A manera general, dos cosas:
- Hay un sistema o algo que está haciendo que los enemigos y que jugador se muevan muuucho más rápido, compara con la rama de main para que veas la diferencia
- No sé si es problema del nombramiento de las variables o de cómo funcione, pero recuerda que el sistema y el componente de parpadeo van a servir para otras cosas como el parpadeo del texto de pause y el de ready. Te recomiendo revisar si entonces system_blink y CBlink podrían funcionar para eso o sí solo están programados para funcionar con las estrellas

2024-05-10 23:30 UTC, Laurarestrepo03 commented
De hecho no son solo los enemigos y el jugador los que se mueven más rápido, las balas también

2024-05-10 23:31 UTC, Laurarestrepo03 commented
Y con respecto a lo de parpadeo, te recomendaría revisar con @miguelangel1021 para saber cómo funciona de momento

2024-05-11 02:22 UTC, leonardo-bp commented
Se revisa código y se corrije error de velocidad del componente de estrellas que estaba afectando a los demás componentes.

Se crea CBlink de manera genérica para que funcione para cualquier parpadeo que se requiera y se ajusta la funcionalidad de pausa. También se ajusta s_rendering ya que contenía lógica de la funcionalidad de pausa y por ser un sistema genérico no debería tener lógica específica para una funcionalidad.

2024-05-11 14:43 UTC, Laurarestrepo03 approved these changes
Muchas gracias por los cambios, ya le velocidad es menor 😎 👍

2024-05-11 14:52 UTC, merged