Feature/8 10 11 sistem game manager
Laurarestrepo03/Ocarina-Galaxian pull request #55
Opened 2024-05-17 23:56 UTC by miguelangel1021

Implementación completa de los estados del juego, desde ready, hasta game over y reinicio el juego. Se modificaron algunos componentes como surface para evitar crear textos (ver como se actualiza la info de un texto para evitar crearlo cada vez que necesita cambiarse). El jugador no se elimina al haber game over, al reiniciar el juego se reasigna su posición a la posición inicial y se hace visible. Se implementó también el sistema de vidas y de nivel (la imagen y texto level).

2024-05-17 23:57 UTC, miguelangel1021 commented
Falta corregir lo el movimiento de las estrellas al realizar pause. Algo que se me olvido, el juego se reinicia en el game over al presionar los botones de fire.

2024-05-18 01:10 UTC, Laurarestrepo03 requested changes
Está súper, gracias! No he revisado completamente, pero sí noté algo que no está funcionando: si te mueres y el juego reinicia, el contador de vidas no sirve. Si necesitas video de eso me dices, me acabó de pasar

2024-05-18 01:16 UTC, Laurarestrepo03 commented
@miguelangel1021 Otra cosa que noté: la bala del jugador en GAME OVER todavía existe y se puede mover (porque está siguiendo al jugador invisible). Creo que esto se puede arreglar solo haciendo invisible la bala:

https://github.com/Laurarestrepo03/Ocarina-Galaxian/assets/69609680/e1835e0c-3556-416a-be66-bfba8b45bec2

2024-05-18 02:02 UTC, Laurarestrepo03 requested changes
Listo, los cambios que hiciste solucionaron lo que te mencioné, gracias! Noté esto sin embargo: cuando se está en el GAME OVER los enemigos siguen disparando, lo cual no deberia pasar (en el ejemplo los enemigos ya no salen del grupo, que en la versión obligatoria sería que no dispararan). No solo eso, sino que las balas que estaban en el GAME OVER se pasan a las demás escenas. En el video puedes notar como la escena estaba vacía pero hay unas balas a la derecha:


https://github.com/Laurarestrepo03/Ocarina-Galaxian/assets/69609680/bd43505a-3459-4c8a-93b1-085b337e0f03

2024-05-18 02:25 UTC, Laurarestrepo03 approved these changes
Muchas gracias por los cambios!

2024-05-18 02:26 UTC, merged